module.exports = Object.freeze({
  PLAYER_RADIUS: 40,
  PLAYER_MAX_HP: 100,
  PLAYER_SPEED: 200,

  CALL_DISTANCE: 300,

  MAP_SIZE: 1500,
  MSG_TYPES: {
    JOIN_GAME: 'join_game',
    GAME_UPDATE: 'update',
    INPUT: 'input',
    EMOTE: 'emote',
    BRDCST_PLAYER_ENTERED: 'entered',
    BRDCST_PLAYER_LEFT: 'left',
  },
  // 3D voxel world (/world) — keep in sync with src/client3d/constants.js
  MSG_TYPES_3D: {
    JOIN: 'w3:join',
    INIT: 'w3:init',
    STATE: 'w3:state',
    PLAYER: 'w3:player',
    LEAVE: 'w3:leave',
    BLOCK: 'w3:block',
    TNT: 'w3:tnt',
    CHAT: 'w3:chat',
    FACE: 'w3:face',
    ATTACK: 'w3:attack',
    HIT: 'w3:hit',
    DEATH: 'w3:death',
    RESPAWN: 'w3:respawn',
  },
  COMBAT_3D: {
    MAX_HP: 100,
    SLASH_DAMAGE: 34,
    STAB_DAMAGE: 55,
    SLASH_RANGE: 2.15,
    STAB_RANGE: 2.55,
    SLASH_COOLDOWN_MS: 420,
    STAB_COOLDOWN_MS: 820,
    SLASH_CONE_DEG: 92,
    STAB_CONE_DEG: 58,
    RESPAWN_MS: 3000,
  },
  EMOJIS: {
    neutral: '😐',
    happy: '😄',
    sad: '😢',
    angry: '🤬',
    fearful: '😱',
    disgusted: '😠',
    surprised: '😮',
  },
  ICE_SERVERS: [
    { url: 'stun:stun.l.google.com:19302' },
    {
      url: 'turn:numb.viagenie.ca',
      credential: 'muazkh',
      username: 'webrtc@live.com',
    },
  ],
});
